{
  "all": true,
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [],
  "extends": "@istanbuljs/nyc-config-typescript",
  "reporter": [
    "lcov",
    "text"
  ],
  "show-process-tree": true
}